# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dr. Katy Williams
email: kawilliams@davidson.edu
description: >- # this means to ignore newlines until "baseurl:"
  Data vis, math, and swimming. Combinations of these are even better.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kawilliams.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  kawilliams

# AI Settings
ai-green: "**GREEN LIGHT**: You may use AI as you wish in this assignment. In fact, I may even encourage you to use AI for this assignment -- see details below." 
ai-yellow: "**YELLOW LIGHT**: You may use AI for certain parts of this assignment or to polish/edit *your original, non-AI work*. Be sure to *carefully* read below to make sure you align with this policy."
ai-red: "**RED LIGHT**: **YOU MAY NOT USE AI for this assignment at all. If you violate this policy, you will earn a 0 for this assignment and the evidence will be submitted to the Honor Council.**"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one


# Collections, like collections of research projects
collections:
  research_pages:
    output: true
    permalink: research/:collection/:name

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
