#!/usr/bin/env python3
"""Regenerate _data/hci_schedule.yml for a new HCI semester.

Jekyll/Liquid has no date-arithmetic filter (and GitHub Pages' safe-mode
build won't run a custom plugin that adds one), so this script is a local
dev helper: run it once per semester, then hand-edit individual entries in
_data/hci_schedule.yml for holiday shifts if a particular Monday/Wednesday
needs to move or be skipped.

Usage:
    python3 scripts/generate_schedule.py 2026-01-12 --weeks 15 > _data/hci_schedule.yml

Then open the generated file and adjust any rows affected by holidays
(e.g. if a week only meets once, delete the extra session line and update
hci.markdown's rowspan for that week).
"""
import argparse
import datetime


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("start", help="First class date, Monday, as YYYY-MM-DD")
    parser.add_argument("--weeks", type=int, default=15, help="Number of weeks (default 15)")
    args = parser.parse_args()

    start = datetime.date.fromisoformat(args.start)
    if start.weekday() != 0:
        parser.error(f"{start} is not a Monday")

    print("# Class session dates -- generated by scripts/generate_schedule.py")
    print("# Cadence: Monday (\"s1\") and Wednesday (\"s2\") each week.")
    print("# Hand-edit any single date below for a holiday shift/exception.")
    print(f'semester_start: "{start.isoformat()}"')
    print()

    for week in range(1, args.weeks + 1):
        monday = start + datetime.timedelta(weeks=week - 1)
        wednesday = monday + datetime.timedelta(days=2)
        print(f'w{week}s1: "{monday.month}/{monday.day}"')
        print(f'w{week}s2: "{wednesday.month}/{wednesday.day}"')


if __name__ == "__main__":
    main()
